package com.emi.nwodcombat.model.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CHARACTER_PERSONALITY_TRAITS".
 */
public class CharacterPersonalityTraits {

    private long id;
    private long idCharacter;
    private long idDemeanor;
    private long idNature;
    private long idVice;
    private long idVirtue;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CharacterPersonalityTraits() {
    }

    public CharacterPersonalityTraits(long id) {
        this.id = id;
    }

    public CharacterPersonalityTraits(long id, long idCharacter, long idDemeanor, long idNature, long idVice, long idVirtue) {
        this.id = id;
        this.idCharacter = idCharacter;
        this.idDemeanor = idDemeanor;
        this.idNature = idNature;
        this.idVice = idVice;
        this.idVirtue = idVirtue;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getIdCharacter() {
        return idCharacter;
    }

    public void setIdCharacter(long idCharacter) {
        this.idCharacter = idCharacter;
    }

    public long getIdDemeanor() {
        return idDemeanor;
    }

    public void setIdDemeanor(long idDemeanor) {
        this.idDemeanor = idDemeanor;
    }

    public long getIdNature() {
        return idNature;
    }

    public void setIdNature(long idNature) {
        this.idNature = idNature;
    }

    public long getIdVice() {
        return idVice;
    }

    public void setIdVice(long idVice) {
        this.idVice = idVice;
    }

    public long getIdVirtue() {
        return idVirtue;
    }

    public void setIdVirtue(long idVirtue) {
        this.idVirtue = idVirtue;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
