package com.emi.nwodcombat.model.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CHARACTER_VICES".
 */
public class CharacterVices {

    private long id;
    private long idCharacter;
    private long idVice;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CharacterVices() {
    }

    public CharacterVices(long id) {
        this.id = id;
    }

    public CharacterVices(long id, long idCharacter, long idVice) {
        this.id = id;
        this.idCharacter = idCharacter;
        this.idVice = idVice;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getIdCharacter() {
        return idCharacter;
    }

    public void setIdCharacter(long idCharacter) {
        this.idCharacter = idCharacter;
    }

    public long getIdVice() {
        return idVice;
    }

    public void setIdVice(long idVice) {
        this.idVice = idVice;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
