package com.emi.nwodcombat.model.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.emi.nwodcombat.model.Record;
// KEEP INCLUDES END

/**
 * Entity mapped to table "NATURE".
 */
public class Nature extends Record {

    private Long idNature;
    /** Not-null value. */
    private String Name;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Nature() {
    }

    public Nature(Long idNature) {
        this.idNature = idNature;
    }

    public Nature(Long idNature, String Name) {
        this.idNature = idNature;
        this.Name = Name;
    }

    public Long getIdNature() {
        return idNature;
    }

    public void setIdNature(Long idNature) {
        this.idNature = idNature;
    }

    /** Not-null value. */
    public String getName() {
        return Name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String Name) {
        this.Name = Name;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
