package com.emi.nwodcombat.model.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.emi.nwodcombat.model.pojos.Record;
// KEEP INCLUDES END
/**
 * Entity mapped to table "NATURE".
 */
public class Nature extends Record  {

    private Long idNature;
    /** Not-null value. */
    private String Name;
    private String RegainOne;
    private String RegainAll;
    private String Description;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Nature() {
    }

    public Nature(Long idNature) {
        this.idNature = idNature;
    }

    public Nature(Long idNature, String Name, String RegainOne, String RegainAll, String Description) {
        this.idNature = idNature;
        this.Name = Name;
        this.RegainOne = RegainOne;
        this.RegainAll = RegainAll;
        this.Description = Description;
    }

    public Long getIdNature() {
        return idNature;
    }

    public void setIdNature(Long idNature) {
        this.idNature = idNature;
    }

    /** Not-null value. */
    public String getName() {
        return Name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String Name) {
        this.Name = Name;
    }

    public String getRegainOne() {
        return RegainOne;
    }

    public void setRegainOne(String RegainOne) {
        this.RegainOne = RegainOne;
    }

    public String getRegainAll() {
        return RegainAll;
    }

    public void setRegainAll(String RegainAll) {
        this.RegainAll = RegainAll;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
