package com.emi.nwodcombat.model.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "VICE".
 */
public class Vice {

    private Long idVice;
    /** Not-null value. */
    private String Name;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Vice() {
    }

    public Vice(Long idVice) {
        this.idVice = idVice;
    }

    public Vice(Long idVice, String Name) {
        this.idVice = idVice;
        this.Name = Name;
    }

    public Long getIdVice() {
        return idVice;
    }

    public void setIdVice(Long idVice) {
        this.idVice = idVice;
    }

    /** Not-null value. */
    public String getName() {
        return Name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String Name) {
        this.Name = Name;
    }

    // KEEP METHODS - put your custom methods here
    public String toString() {
        return getName();
    }
    // KEEP METHODS END

}
