package com.emi.nwodcombat.model.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.emi.nwodcombat.model.Record;
// KEEP INCLUDES END
/**
 * Entity mapped to table "VIRTUE".
 */
public class Virtue extends Record  {

    private Long idVirtue;
    /** Not-null value. */
    private String Name;
    /** Not-null value. */
    private String RegainAll;
    private String Description;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Virtue() {
    }

    public Virtue(Long idVirtue) {
        this.idVirtue = idVirtue;
    }

    public Virtue(Long idVirtue, String Name, String RegainAll, String Description) {
        this.idVirtue = idVirtue;
        this.Name = Name;
        this.RegainAll = RegainAll;
        this.Description = Description;
    }

    public Long getIdVirtue() {
        return idVirtue;
    }

    public void setIdVirtue(Long idVirtue) {
        this.idVirtue = idVirtue;
    }

    /** Not-null value. */
    public String getName() {
        return Name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String Name) {
        this.Name = Name;
    }

    /** Not-null value. */
    public String getRegainAll() {
        return RegainAll;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRegainAll(String RegainAll) {
        this.RegainAll = RegainAll;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
