package com.emi.nwodcombat.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.emi.nwodcombat.model.db.CharacterVirtues;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHARACTER_VIRTUES".
*/
public class CharacterVirtuesDao extends AbstractDao<CharacterVirtues, Long> {

    public static final String TABLENAME = "CHARACTER_VIRTUES";

    /**
     * Properties of entity CharacterVirtues.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property IdCharacter = new Property(1, long.class, "idCharacter", false, "ID_CHARACTER");
        public final static Property IdVirtue = new Property(2, long.class, "idVirtue", false, "ID_VIRTUE");
    };


    public CharacterVirtuesDao(DaoConfig config) {
        super(config);
    }
    
    public CharacterVirtuesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHARACTER_VIRTUES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"ID_CHARACTER\" INTEGER NOT NULL ," + // 1: idCharacter
                "\"ID_VIRTUE\" INTEGER NOT NULL );"); // 2: idVirtue
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHARACTER_VIRTUES\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CharacterVirtues entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getIdCharacter());
        stmt.bindLong(3, entity.getIdVirtue());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CharacterVirtues readEntity(Cursor cursor, int offset) {
        CharacterVirtues entity = new CharacterVirtues( //
            cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // idCharacter
            cursor.getLong(offset + 2) // idVirtue
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CharacterVirtues entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setIdCharacter(cursor.getLong(offset + 1));
        entity.setIdVirtue(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CharacterVirtues entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CharacterVirtues entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
