package com.emi.nwodcombat.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.emi.nwodcombat.model.db.CharacterVices;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHARACTER_VICES".
*/
public class CharacterVicesDao extends AbstractDao<CharacterVices, Long> {

    public static final String TABLENAME = "CHARACTER_VICES";

    /**
     * Properties of entity CharacterVices.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property IdCharacter = new Property(1, long.class, "idCharacter", false, "ID_CHARACTER");
        public final static Property IdVice = new Property(2, long.class, "idVice", false, "ID_VICE");
    };


    public CharacterVicesDao(DaoConfig config) {
        super(config);
    }
    
    public CharacterVicesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHARACTER_VICES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"ID_CHARACTER\" INTEGER NOT NULL ," + // 1: idCharacter
                "\"ID_VICE\" INTEGER NOT NULL );"); // 2: idVice
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHARACTER_VICES\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CharacterVices entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getIdCharacter());
        stmt.bindLong(3, entity.getIdVice());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CharacterVices readEntity(Cursor cursor, int offset) {
        CharacterVices entity = new CharacterVices( //
            cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // idCharacter
            cursor.getLong(offset + 2) // idVice
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CharacterVices entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setIdCharacter(cursor.getLong(offset + 1));
        entity.setIdVice(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CharacterVices entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CharacterVices entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
