package com.emi.nwodcombat.greendao;

import android.database.sqlite.SQLiteDatabase;

import com.emi.nwodcombat.model.db.Character;
import com.emi.nwodcombat.model.db.CharacterPersonalityTraits;
import com.emi.nwodcombat.model.db.Demeanor;
import com.emi.nwodcombat.model.db.Nature;
import com.emi.nwodcombat.model.db.Vice;
import com.emi.nwodcombat.model.db.Virtue;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig characterDaoConfig;
    private final DaoConfig demeanorDaoConfig;
    private final DaoConfig natureDaoConfig;
    private final DaoConfig viceDaoConfig;
    private final DaoConfig virtueDaoConfig;
    private final DaoConfig characterPersonalityTraitsDaoConfig;

    private final CharacterDao characterDao;
    private final DemeanorDao demeanorDao;
    private final NatureDao natureDao;
    private final ViceDao viceDao;
    private final VirtueDao virtueDao;
    private final CharacterPersonalityTraitsDao characterPersonalityTraitsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        characterDaoConfig = daoConfigMap.get(CharacterDao.class).clone();
        characterDaoConfig.initIdentityScope(type);

        demeanorDaoConfig = daoConfigMap.get(DemeanorDao.class).clone();
        demeanorDaoConfig.initIdentityScope(type);

        natureDaoConfig = daoConfigMap.get(NatureDao.class).clone();
        natureDaoConfig.initIdentityScope(type);

        viceDaoConfig = daoConfigMap.get(ViceDao.class).clone();
        viceDaoConfig.initIdentityScope(type);

        virtueDaoConfig = daoConfigMap.get(VirtueDao.class).clone();
        virtueDaoConfig.initIdentityScope(type);

        characterPersonalityTraitsDaoConfig = daoConfigMap.get(CharacterPersonalityTraitsDao.class).clone();
        characterPersonalityTraitsDaoConfig.initIdentityScope(type);

        characterDao = new CharacterDao(characterDaoConfig, this);
        demeanorDao = new DemeanorDao(demeanorDaoConfig, this);
        natureDao = new NatureDao(natureDaoConfig, this);
        viceDao = new ViceDao(viceDaoConfig, this);
        virtueDao = new VirtueDao(virtueDaoConfig, this);
        characterPersonalityTraitsDao = new CharacterPersonalityTraitsDao(characterPersonalityTraitsDaoConfig, this);

        registerDao(Character.class, characterDao);
        registerDao(Demeanor.class, demeanorDao);
        registerDao(Nature.class, natureDao);
        registerDao(Vice.class, viceDao);
        registerDao(Virtue.class, virtueDao);
        registerDao(CharacterPersonalityTraits.class, characterPersonalityTraitsDao);
    }
    
    public void clear() {
        characterDaoConfig.getIdentityScope().clear();
        demeanorDaoConfig.getIdentityScope().clear();
        natureDaoConfig.getIdentityScope().clear();
        viceDaoConfig.getIdentityScope().clear();
        virtueDaoConfig.getIdentityScope().clear();
        characterPersonalityTraitsDaoConfig.getIdentityScope().clear();
    }

    public CharacterDao getCharacterDao() {
        return characterDao;
    }

    public DemeanorDao getDemeanorDao() {
        return demeanorDao;
    }

    public NatureDao getNatureDao() {
        return natureDao;
    }

    public ViceDao getViceDao() {
        return viceDao;
    }

    public VirtueDao getVirtueDao() {
        return virtueDao;
    }

    public CharacterPersonalityTraitsDao getCharacterPersonalityTraitsDao() {
        return characterPersonalityTraitsDao;
    }

}
