package com.emi.nwodcombat.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.emi.nwodcombat.model.db.CharacterPersonalityTraits;
import com.emi.nwodcombat.model.db.Nature;

import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NATURE".
*/
public class NatureDao extends AbstractDao<Nature, Long> {

    public static final String TABLENAME = "NATURE";

    /**
     * Properties of entity Nature.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property IdNature = new Property(0, Long.class, "idNature", true, "ID_NATURE");
        public final static Property Name = new Property(1, String.class, "Name", false, "NAME");
    };

    private Query<Nature> character_NatureListQuery;

    public NatureDao(DaoConfig config) {
        super(config);
    }
    
    public NatureDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NATURE\" (" + //
                "\"ID_NATURE\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: idNature
                "\"NAME\" TEXT NOT NULL );"); // 1: Name
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NATURE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Nature entity) {
        stmt.clearBindings();
 
        Long idNature = entity.getIdNature();
        if (idNature != null) {
            stmt.bindLong(1, idNature);
        }
        stmt.bindString(2, entity.getName());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Nature readEntity(Cursor cursor, int offset) {
        Nature entity = new Nature( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // idNature
            cursor.getString(offset + 1) // Name
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Nature entity, int offset) {
        entity.setIdNature(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Nature entity, long rowId) {
        entity.setIdNature(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Nature entity) {
        if(entity != null) {
            return entity.getIdNature();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "natureList" to-many relationship of Character. */
    public List<Nature> _queryCharacter_NatureList(Long idCharacter) {
        synchronized (this) {
            if (character_NatureListQuery == null) {
                QueryBuilder<Nature> queryBuilder = queryBuilder();
                queryBuilder.join(CharacterPersonalityTraits.class, CharacterPersonalityTraitsDao.Properties.IdNature)
                    .where(CharacterPersonalityTraitsDao.Properties.IdCharacter.eq(idCharacter));
                character_NatureListQuery = queryBuilder.build();
            }
        }
        Query<Nature> query = character_NatureListQuery.forCurrentThread();
        query.setParameter(0, idCharacter);
        return query.list();
    }

}
