package com.emi.nwodcombat.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.emi.nwodcombat.model.db.CharacterPersonalityTraits;
import com.emi.nwodcombat.model.db.Vice;

import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VICE".
*/
public class ViceDao extends AbstractDao<Vice, Long> {

    public static final String TABLENAME = "VICE";

    /**
     * Properties of entity Vice.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property IdVice = new Property(0, Long.class, "idVice", true, "ID_VICE");
        public final static Property Name = new Property(1, String.class, "Name", false, "NAME");
        public final static Property RegainOne = new Property(2, String.class, "RegainOne", false, "REGAIN_ONE");
        public final static Property Description = new Property(3, String.class, "Description", false, "DESCRIPTION");
    };

    private Query<Vice> character_ViceListQuery;

    public ViceDao(DaoConfig config) {
        super(config);
    }
    
    public ViceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VICE\" (" + //
                "\"ID_VICE\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: idVice
                "\"NAME\" TEXT NOT NULL ," + // 1: Name
                "\"REGAIN_ONE\" TEXT NOT NULL ," + // 2: RegainOne
                "\"DESCRIPTION\" TEXT);"); // 3: Description
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VICE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Vice entity) {
        stmt.clearBindings();
 
        Long idVice = entity.getIdVice();
        if (idVice != null) {
            stmt.bindLong(1, idVice);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getRegainOne());
 
        String Description = entity.getDescription();
        if (Description != null) {
            stmt.bindString(4, Description);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Vice readEntity(Cursor cursor, int offset) {
        Vice entity = new Vice( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // idVice
            cursor.getString(offset + 1), // Name
            cursor.getString(offset + 2), // RegainOne
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // Description
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Vice entity, int offset) {
        entity.setIdVice(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setRegainOne(cursor.getString(offset + 2));
        entity.setDescription(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Vice entity, long rowId) {
        entity.setIdVice(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Vice entity) {
        if(entity != null) {
            return entity.getIdVice();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "viceList" to-many relationship of Character. */
    public List<Vice> _queryCharacter_ViceList(Long idCharacter) {
        synchronized (this) {
            if (character_ViceListQuery == null) {
                QueryBuilder<Vice> queryBuilder = queryBuilder();
                queryBuilder.join(CharacterPersonalityTraits.class, CharacterPersonalityTraitsDao.Properties.IdVice)
                    .where(CharacterPersonalityTraitsDao.Properties.IdCharacter.eq(idCharacter));
                character_ViceListQuery = queryBuilder.build();
            }
        }
        Query<Vice> query = character_ViceListQuery.forCurrentThread();
        query.setParameter(0, idCharacter);
        return query.list();
    }

}
